import '@/styles/globals.css'

import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import type { Metadata } from "next";
import { Header } from '@/components/header'
import { ThemeProvider } from "@/components/theme-provider"
import { TooltipProvider } from '@/components/ui/tooltip';
import { cn } from '@/lib/utils'


export const metadata: Metadata = {
  title: "Hi, RAG",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('font-sans antialiased', GeistSans.variable, GeistMono.variable)}>
          <div className="flex flex-col min-h-screen">
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem  disableTransitionOnChange>
              <Header />
              <TooltipProvider>
                <main className="flex flex-col flex-1 bg-muted/50">{children}</main>
              </TooltipProvider>
            </ThemeProvider>
          </div>
      </body>
    </html>
  );
}
